### ISSUE TITLE
Table Manager and Multicolumn Listbox are Strongly Coupled 

### ISSUE THREAD

**Issue by knoxberry** [LabVIEW-DCAF/Table-API#12]
ATM data should probably be stored at the child class level.

**Comment by becega** [comment]
The new table manager api, uses either the multi column list box or the datagrid table (but that one has a couple of unhandled exceptions so we are using the multi column.
Most of the behaviors of the table are change either by overrides on the node class of your module, or through callbacks. 
What are you trying to do?

**Comment by knoxberry** [comment]
I was looking to create a multi-column listbox to show and modify expansion chassis. The table manager defines the ATM in its private class data. The init function also requires events and references to classes that may or may not be relevant for the MCLB you are trying to create (Engine, Config, etc). It would be nice to have a table manager that was agnostic of the framework it's being used in and define functionality in child classes. What do you think?

For the time being I can make use of the Table Manager and the MCLB child class for the Scan Engine module by using overrides or callbacks specific to mapping tags.

**Comment by becega** [comment]
I agree at some point it would be nice to have it more decoupled, and we tested that at some point, but in this case the purpose is to allow easier development for DCAF modules.  By having this coupling it is able to simplify the abstraction that being decoupled would require.  The ATM is for managing tags, and uses the engine to get the tags that is why we have the object there. WE wanted to simplify what was required on the main VI and the table covers most of the use cases for the modules. 
 Also the problem with that is if you needed to inherit from the class now a normal tagbus module project will require 4 classes rather than 3. 
At some point I wanted just to couple it to the config class, but it requires more information. 
THe ATM is for tags only, if you want to add chassis or something similar you can inherit from the colum class and create a new column with what you want. Right now we have string enum and tags, at some point we might also add string ring which probably is what you want.

**Comment by becega** [comment]
If you want functionality similar to the ATM but with something else we need to expand the colum and create a new type.
