### ISSUE TITLE
Add Right Click menu and callbacks

### ISSUE THREAD

**Issue by becega** [LabVIEW-DCAF/Table-API#3]
IF we want options like right click add or rick click delete we need callbacks. WE can probably add just a configuration Vi that defines the menu name and a reference to the callback

**Comment by Beazurt** [comment]
I think we need this feature before we standardize on the Table in all UIs. Many of our UIs today have right-click options for adding, editing, or deleting rows. This functionality is nice to have, natural for users, and can eliminate the need for many buttons on the UI. Fewer buttons on the UI also makes the resize problem much easier to solve.

I think a configuration VI with a pairing of the menu name and callback VI would work great. The only other thing I can think of is that we need a different configuration for empty rows than for existing rows. Ex. existing rows show Add, Edit, Delete. Empty rows only show Add.

**Comment by becega** [comment]
Probably we should leave both the buttons and the right click, or we need a good way to make sure people right click on the table.

**Comment by Beazurt** [comment]
If everything uses the table, and all the tables use right-click, then I
don't think we will need to teach people this, it will be second-nature.
Today right-click works in some places and not in others and I think that
is a lot more confusing. We could only use buttons instead of
right-clicking, but buttons have a lot of disadvantages:

Buttons use up more UI real-estate which make the tables smaller
Buttons need icons, and these are harder to standardize
Buttons can be put anywhere on the UI, this is also harder to standardize
Buttons require new event cases in the editor node event structure. I think
this makes them harder to implement
Buttons make resizing a lot harder. If we have no buttons, and the datagrid
can resize automatically, then our editor can resize without us having to
do any extra programming

Again this is my personal preference, but I think we'd be a lot better off
if we got rid of as many buttons as possible and encouraged people to do
everything through the table. I'd rather we implement this before we scrub
all of the UIs, but I don't know how much effort it will take.

**Comment by smithed** [comment]
agree with burt, if you add right clicks everywhere get rid of the buttons. as for implementation I haven't really looked at the table but you could do it the way the I did the custom right click on the main tree. Nodes can register their own options when you right click (callback A) and then nodes implement a handler for that (callback B) which takes the string tag associated with the right click option.

Also you should totally add drag and drop! I dunno if you guys have ever done it this way but I found out this works not too long ago:
http://zone.ni.com/reference/en-XX/help/371361J-01/lvhowto/drag_and_drop_programmatic_update/
You could do sweet things like loading from excel ;).

**Comment by becega** [comment]
Will add a option to add custom strings to the right click menu, but will not add callbacks I will pass the selection out as a user event that will be handle on the parent class, as there should be similar code already there.

**Comment by becega** [comment]
Added the right click menu Option, its configured in the init.VI, and it passed the event to the editor node ui to be handled with information of what was selected, the line name, and the row and column
