### ISSUE TITLE
Changing a value and clicking outside of the cell doesn't throw value change event

### ISSUE THREAD

**Issue by tannerblair** [LabVIEW-DCAF/Table-API#30]
If I change a value in a cell, then click out of that cell the displayed value changes but the callback isn't executed.

**Comment by tannerblair** [comment]
![image](https://cloud.githubusercontent.com/assets/12645089/21231148/d19fa58c-c2ac-11e6-9879-d0ce83bdaabe.png)

That fixes it.

**Comment by jwgorman** [comment]
This should move to TagEditorCore repo

**Comment by jwgorman** [comment]
Acceptance Criteria
- All cell value changes should run the call back

**Comment by theSloopJohnB** [comment]
This was fixed by this commit: https://github.com/LabVIEW-DCAF/TagEditorCore/commit/c73abd9e77dc9af20d821cd4f929ba206a708f81

Looks like the issue was not closed at the time. No biggie.

I verified that the current state of the the Event Handler VI matches what @tannerblair posted in his screenshot.
